# Generated by Django 4.2.9 on 2024-01-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=32, null=True, unique=True, verbose_name='이메일')),
                ('user_pw', models.CharField(max_length=128, verbose_name='비밀번호')),
                ('user_name', models.CharField(max_length=32, unique=True, verbose_name='이름')),
                ('user_register_dttm', models.DateTimeField(auto_now_add=True, verbose_name='계정 생성시간')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
