# Generated by Django 4.2.9 on 2024-01-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_userinfo_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=32, unique=True, verbose_name='이메일')),
                ('user_pw', models.CharField(max_length=128, verbose_name='비밀번호')),
                ('user_name', models.CharField(max_length=32, unique=True, verbose_name='이름')),
                ('user_register_dttm', models.DateTimeField(auto_now_add=True, verbose_name='계정 생성시간')),
            ],
            options={
                'verbose_name': '유저',
                'verbose_name_plural': '유저',
                'db_table': 'user',
            },
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
