# Generated by Django 4.2.9 on 2024-01-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_alter_customuser_options_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(max_length=50, unique=True, verbose_name='닉네임'),
        ),
    ]
