# Generated by Django 4.2.9 on 2024-01-22 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_customuser_delete_userinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
