# Generated by Django 4.2.9 on 2024-02-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_alter_customuser_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='생년월일'),
        ),
    ]
