# Generated by Django 4.2.9 on 2024-01-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0004_rename_customuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_email',
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='default', max_length=32, unique=True, verbose_name='아이디'),
        ),
    ]
