# Generated by Django 4.2.9 on 2024-01-25 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_alter_post_options_post_bookmarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='bookmarked_by',
            new_name='bookmarked',
        ),
        migrations.RemoveField(
            model_name='post',
            name='bookmarks',
        ),
    ]
